package moe.styx.styx2m.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006D31)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF59EA83)
val onPrimaryContainerLight = Color(0xFF00461D)
val secondaryLight = Color(0xFF611E9A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF8749C1)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF00561C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF327C3D)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF3FCF0)
val onBackgroundLight = Color(0xFF161D16)
val surfaceLight = Color(0xFFF3FCF0)
val onSurfaceLight = Color(0xFF161D16)
val surfaceVariantLight = Color(0xFFD8E7D5)
val onSurfaceVariantLight = Color(0xFF3D4A3D)
val outlineLight = Color(0xFF6D7B6C)
val outlineVariantLight = Color(0xFFBCCBBA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B322B)
val inverseOnSurfaceLight = Color(0xFFEBF3E7)
val inversePrimaryLight = Color(0xFF4FE17B)
val surfaceDimLight = Color(0xFFD4DCD1)
val surfaceBrightLight = Color(0xFFF3FCF0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEEF6EA)
val surfaceContainerLight = Color(0xFFE8F0E4)
val surfaceContainerHighLight = Color(0xFFE2EBDF)
val surfaceContainerHighestLight = Color(0xFFDDE5D9)

val primaryLightMediumContrast = Color(0xFF004E21)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF00873E)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF5F1C99)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF8749C1)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF004E19)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF327C3D)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF3FCF0)
val onBackgroundLightMediumContrast = Color(0xFF161D16)
val surfaceLightMediumContrast = Color(0xFFF3FCF0)
val onSurfaceLightMediumContrast = Color(0xFF161D16)
val surfaceVariantLightMediumContrast = Color(0xFFD8E7D5)
val onSurfaceVariantLightMediumContrast = Color(0xFF394639)
val outlineLightMediumContrast = Color(0xFF556355)
val outlineVariantLightMediumContrast = Color(0xFF707E70)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B322B)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEBF3E7)
val inversePrimaryLightMediumContrast = Color(0xFF4FE17B)
val surfaceDimLightMediumContrast = Color(0xFFD4DCD1)
val surfaceBrightLightMediumContrast = Color(0xFFF3FCF0)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEEF6EA)
val surfaceContainerLightMediumContrast = Color(0xFFE8F0E4)
val surfaceContainerHighLightMediumContrast = Color(0xFFE2EBDF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDDE5D9)

val primaryLightHighContrast = Color(0xFF00290E)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004E21)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF36005F)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5F1C99)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002909)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF004E19)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF3FCF0)
val onBackgroundLightHighContrast = Color(0xFF161D16)
val surfaceLightHighContrast = Color(0xFFF3FCF0)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD8E7D5)
val onSurfaceVariantLightHighContrast = Color(0xFF1A271C)
val outlineLightHighContrast = Color(0xFF394639)
val outlineVariantLightHighContrast = Color(0xFF394639)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B322B)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFACFFB8)
val surfaceDimLightHighContrast = Color(0xFFD4DCD1)
val surfaceBrightLightHighContrast = Color(0xFFF3FCF0)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEEF6EA)
val surfaceContainerLightHighContrast = Color(0xFFE8F0E4)
val surfaceContainerHighLightHighContrast = Color(0xFFE2EBDF)
val surfaceContainerHighestLightHighContrast = Color(0xFFDDE5D9)

val primaryDark = Color(0xFFA3FFB2)
val onPrimaryDark = Color(0xFF003916)
val primaryContainerDark = Color(0xFF47DA75)
val onPrimaryContainerDark = Color(0xFF003B17)
val secondaryDark = Color(0xFFDEB7FF)
val onSecondaryDark = Color(0xFF4A007F)
val secondaryContainerDark = Color(0xFF7E3FB7)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFF8BD88E)
val onTertiaryDark = Color(0xFF003910)
val tertiaryContainerDark = Color(0xFF126226)
val onTertiaryContainerDark = Color(0xFFE4FFDF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E150E)
val onBackgroundDark = Color(0xFFDDE5D9)
val surfaceDark = Color(0xFF0E150E)
val onSurfaceDark = Color(0xFFDDE5D9)
val surfaceVariantDark = Color(0xFF3D4A3D)
val onSurfaceVariantDark = Color(0xFFBCCBBA)
val outlineDark = Color(0xFF869585)
val outlineVariantDark = Color(0xFF3D4A3D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE5D9)
val inverseOnSurfaceDark = Color(0xFF2B322B)
val inversePrimaryDark = Color(0xFF006D31)
val surfaceDimDark = Color(0xFF0E150E)
val surfaceBrightDark = Color(0xFF333B33)
val surfaceContainerLowestDark = Color(0xFF091009)
val surfaceContainerLowDark = Color(0xFF161D16)
val surfaceContainerDark = Color(0xFF1A211A)
val surfaceContainerHighDark = Color(0xFF242C24)
val surfaceContainerHighestDark = Color(0xFF2F372F)

val primaryDarkMediumContrast = Color(0xFFA3FFB2)
val onPrimaryDarkMediumContrast = Color(0xFF003815)
val primaryContainerDarkMediumContrast = Color(0xFF47DA75)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000A02)
val secondaryDarkMediumContrast = Color(0xFFE1BDFF)
val onSecondaryDarkMediumContrast = Color(0xFF250044)
val secondaryContainerDarkMediumContrast = Color(0xFFB374EE)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF8FDD92)
val onTertiaryDarkMediumContrast = Color(0xFF001B05)
val tertiaryContainerDarkMediumContrast = Color(0xFF56A15D)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E150E)
val onBackgroundDarkMediumContrast = Color(0xFFDDE5D9)
val surfaceDarkMediumContrast = Color(0xFF0E150E)
val onSurfaceDarkMediumContrast = Color(0xFFF5FDF1)
val surfaceVariantDarkMediumContrast = Color(0xFF3D4A3D)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC0CFBE)
val outlineDarkMediumContrast = Color(0xFF98A797)
val outlineVariantDarkMediumContrast = Color(0xFF798778)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDDE5D9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF242C24)
val inversePrimaryDarkMediumContrast = Color(0xFF005424)
val surfaceDimDarkMediumContrast = Color(0xFF0E150E)
val surfaceBrightDarkMediumContrast = Color(0xFF333B33)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF091009)
val surfaceContainerLowDarkMediumContrast = Color(0xFF161D16)
val surfaceContainerDarkMediumContrast = Color(0xFF1A211A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF242C24)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF2F372F)

val primaryDarkHighContrast = Color(0xFFF0FFED)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF54E57E)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9FC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE1BDFF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF0FFEB)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF8FDD92)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0E150E)
val onBackgroundDarkHighContrast = Color(0xFFDDE5D9)
val surfaceDarkHighContrast = Color(0xFF0E150E)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3D4A3D)
val onSurfaceVariantDarkHighContrast = Color(0xFFF0FFED)
val outlineDarkHighContrast = Color(0xFFC0CFBE)
val outlineVariantDarkHighContrast = Color(0xFFC0CFBE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDDE5D9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF003212)
val surfaceDimDarkHighContrast = Color(0xFF0E150E)
val surfaceBrightDarkHighContrast = Color(0xFF333B33)
val surfaceContainerLowestDarkHighContrast = Color(0xFF091009)
val surfaceContainerLowDarkHighContrast = Color(0xFF161D16)
val surfaceContainerDarkHighContrast = Color(0xFF1A211A)
val surfaceContainerHighDarkHighContrast = Color(0xFF242C24)
val surfaceContainerHighestDarkHighContrast = Color(0xFF2F372F)


val seed = Color(0xFF4FE17B)

val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)